class ValidationError(Exception):
    pass

class StorageError(Exception):
    pass